name: lego_rental_frontend
description: A new Flutter project.
publish_to: none

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.2.1
  http: ^1.6.0
  shared_preferences: ^2.2.3
  image_picker: ^1.1.2
  image_picker_for_web: ^3.0.4
  dio: ^5.4.0
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/bj_lego.JPG
    - assets/images/Untitled-2.png
